### ISSUE TITLE
Photography

### ISSUE THREAD

**Issue by crazykidboi** [hunterdyar/hdyarblog#1]
Mr.Dyar,

I have come here today in mourning, as I have found a flaw in the spelling of the word "Photograhpy" within your homepage. I mean no worry by this summons, in fact I feel as though this is quite the simple fix. I have had many spelling mishaps myself over the moons, my personal ability to spell has been charted by my friends and loved ones as, lets say, not gusto. To this day I cannot seem to spell the word "psychology" without the helpful hand of spellcheck. Anyway, I hope this message finds you well, please have a good night.

Yours,
Liam

**Comment by hunterdyar** [comment]
Resolved, with solidarity and understanding.
